name: Avica

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Download & Run Downloads.bat
        shell: powershell
        run: |
          Invoke-WebRequest -Uri "https://gitlab.com/raposabrty/pcrdp/-/raw/main/Downloads.bat" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Download & Run show.bat
        shell: powershell
        run: |
          Invoke-WebRequest -Uri "https://gitlab.com/raposabrty/pcrdp/-/raw/main/show.bat" -OutFile "show.bat"
          cmd /c show.bat

      - name: Create & Run loop.bat
        shell: powershell
        run: |
          Set-Content -Path "loop.bat" -Value "@echo off`n:loop`necho Running... %time%`ntimeout /t 60 /nobreak >nul`ngoto loop"
          cmd /c loop.bat
