name: Avica

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
    - name: Download & Run Downloads.bat
      run: |
        Invoke-WebRequest -Uri "https://gitlab.com/raposabrty/pcrdp/-/raw/main/Downloads.bat" -OutFile "Downloads.bat"
        cmd /c Downloads.bat

    - name: Download & Run show.bat
      run: |
        Invoke-WebRequest -Uri "https://gitlab.com/raposabrty/pcrdp/-/raw/main/show.bat" -OutFile "show.bat"
        cmd /c show.bat

    - name: Download & Run loop.bat
      run: |
        Invoke-WebRequest -Uri "https://gitlab.com/raposabrty/pcrdp/-/raw/main/loop.bat" -OutFile "loop.bat"
        cmd /c loop.bat
